[package]
name = "spec_typeck"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vir = { path = "../vir" }

[package.metadata.rust-analyzer]
rustc_private = true
