[package]
name = "rustc_trait_selection_verus_fork"
version = "0.0.0"
edition = "2021"

[dependencies]
# tidy-alphabetical-start
bitflags = "2.4.1"
itertools = "0.12"
#smallvec = { version = "1.8.1", features = ["union", "may_dangle"] }
tracing = "0.1"
